### ISSUE TITLE
pluggable "index file serving" crosspost

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/broccoli-middleware#2]
https://github.com/ember-fastboot/ember-cli-fastboot/issues/274

**Comment by kratiahuja** [comment]
This RFC will resolve this issue: https://github.com/ember-cli/rfcs/pull/80

**Comment by kratiahuja** [comment]
RFC and related implementation is merged and released in `ember-cli@2.12.0-beta.1`. Closing this.
